---
- name: Manage EC2 instance
  hosts: ec2host
  become: false
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false

  tasks:
      - name: Get version of yum package manager
        ansible.builtin.shell: |
            grep ^__version__ /usr/lib/python*/site-packages/yum/__init__.py
        register: cmd_out
        changed_when: false
      - name: Show yum version
        debug: msg="yum version check - {{ cmd_out.stdout }}"
      - name: Get version of python
        ansible.builtin.shell: python --version
        register: cmd_out
        changed_when: false
      - name: Show python version
        debug: msg="python version = {{ cmd_out.stdout }}"
      - name: Install python
        yum:
          name: python3
          state: present
        become: true
      - name: Install python3-pip
        yum:
          name: python3-pip
          state: present
        become: true
      - name: Get version of python3
        ansible.builtin.shell: python3 --version
        register: cmd_out
        changed_when: false
      - name: Show python3 version
        debug: msg="python3 version = {{ cmd_out.stdout }}"
      - name: Check version of python3-pip
        ansible.builtin.shell: pip3 --version
        register: cmd_out
        changed_when: false
      - name: Show python3 version
        debug: msg="{{ cmd_out.stdout }}"
      - name: Install Python packages
        pip:
          name: "{{ item }}"
          state: present
          executable: pip3
        with_items:
          - tweepy==4.4.0
          - python-dotenv==0.19.2
          - psutil==5.8.0
      - name: Get all installed python packages
        ansible.builtin.shell: pip3 freeze
        register: cmd_out
        changed_when: false
      - name: Show python packages
        debug: msg="{{ cmd_out.stdout }}"
      - name: Copy Python twitter streamer script
        ansible.builtin.copy:
          src: twitter_s3.py
          dest: twitter_s3.py
